name: praktek2
description: "A new Flutter project."
publish_to: "none" # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2 # Ensure this matches your Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  google_fonts: ^6.1.0
  intl: ^0.19.0
  image_picker: ^1.0.4
  firebase_storage: ^11.6.6
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  country_picker: ^2.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/loading.png
