name: praktek2
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2 # Ensure this matches your Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4 # Using the newer version provided in your first block
  google_fonts: ^6.1.0
  intl: ^0.19.0 # Added for date/time formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png